src/Entity/Client.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ClientRepository")
 */
class Client
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $name;

    /**
     * @ORM\Column(type="text")
     */
    private $last_name;

    /**
     * @ORM\Column(type="text")
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $zip_code;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $state;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $email;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Reservation", mappedBy="client")
     */
    private $reservations;

    public function __construct()
    {
        $this->reservations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getZipCode(): ?string
    {
        return $this->zip_code;
    }

    public function setZipCode(string $zip_code): self
    {
        $this->zip_code = $zip_code;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getState(): ?string
    {
        return $this->state;
    }

    public function setState(string $state): self
    {
        $this->state = $state;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * @return Collection|Reservation[]
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): self
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations[] = $reservation;
            $reservation->setClient($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): self
    {
        if ($this->reservations->contains($reservation)) {
            $this->reservations->removeElement($reservation);
            // set the owning side to null (unless already changed)
            if ($reservation->getClient() === $this) {
                $reservation->setClient(null);
            }
        }

        return $this;
    }

}

src/Entity/Reservation.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ReservationRepository")
 */
class Reservation
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_in;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_out;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Client", inversedBy="reservations")
     */
    private $client;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Room", inversedBy="reservations")
     */
    private $room;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateIn(): ?\DateTimeInterface
    {
        return $this->date_in;
    }

    public function setDateIn(\DateTimeInterface $date_in): self
    {
        $this->date_in = $date_in;

        return $this;
    }

    public function getDateOut(): ?\DateTimeInterface
    {
        return $this->date_out;
    }

    public function setDateOut(\DateTimeInterface $date_out): self
    {
        $this->date_out = $date_out;

        return $this;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): self
    {
        $this->client = $client;

        return $this;
    }

    public function getRoom(): ?Room
    {
        return $this->room;
    }

    public function setRoom(?Room $room): self
    {
        $this->room = $room;

        return $this;
    }
}

src/Controller/ReservationController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\Reservation;

class ReservationController extends AbstractController
{
    /**
     * @Route("/reservation", name="reservation")
     */
    public function index()
    {

        $data[] = [];
        $reservation_repo = $this     
                                ->getDoctrine()
                                ->getRepository('App:Reservation');
        
        $reservations = $reservation_repo->getCurrentReservations();
        $data['reservations'] = $reservations;

        return $this->render(   'reservation/index.html.twig', 
                                $data );
    }

    /**
     * @Route("/reservation/{id_client}", name="booking")
     */
    public function book(Request $request, $id_client)
    {
        $data = [];
        $data['rooms'] = null;
        $data['dates']['from'] = '';
        $data['dates']['to'] = '';
        $form = $this   ->createFormBuilder()
                        ->add('dateFrom')
                        ->add('dateTo')
                        ->getForm();
        
        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            $form_data = $form->getData();

            $data['dates']['from'] = $form_data['dateFrom'];
            $data['dates']['to'] = $form_data['dateTo'];

            $em = $this->getDoctrine()->getManager();
            $rooms = $em->getRepository('App:Room')
                ->getAvailableRooms($form_data['dateFrom'], $form_data['dateTo']);   

            $data['rooms'] = $rooms;

        } 
        
        $client = $this
                        ->getDoctrine()
                        ->getRepository('App:Client')
                        ->find($id_client);

        

        
        $data['client'] = $client;
        return $this->render(   'reservation/book.html.twig',
                                $data );

    }

    /**
     * @Route("/book_Room/{id_client}/{id_room}/{date_in}/{date_out}", name="book_Room")
     */
    public function bookRoom($id_client, $id_room, $date_in, $date_out)
    {
        $reservation = new Reservation();
        $date_start = new \DateTime($date_in);
        $date_end = new \DateTime($date_out);
        $reservation->setDateIn($date_start);
        $reservation->setDateOut($date_end);

        $client = $this
                    ->getDoctrine()
                    ->getRepository('App:Client')
                    ->find($id_client);

        $room = $this
                    ->getDoctrine()
                    ->getRepository('App:Room')
                    ->find($id_room);

        $em = $this
                ->getDoctrine()
                ->getManager();

        $room_availability = $em
                                ->getRepository('App:Room')
                                ->checkRoomAvailability($id_room,$date_in, $date_out);

        //Check if there are booked rooms with those dates
        if(!$room_availability)
        {
            //Room is available
            $reservation->setClient($client);
            $reservation->setRoom($room);

            $em->persist($reservation);
            $em->flush();
            
            return $this->redirectToRoute('reservation');

        }else
        {

            throw new \Exception('Room is already booked!');

        }  

    }

     /**
     * @Route("/reservation/cancel/{reservation_id}", name="cancel_booking")
     */
    public function cancel($reservation_id)
    {
        $em = $this
                ->getDoctrine()
                ->getManager();

        $reservation = $em->getReference('App:Reservation', $reservation_id);
        $em->remove($reservation);
        $em->flush();

        return $this->redirectToRoute('reservation');


    }

}

templates/reservation/book.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <div class="row">
      <div class="medium-12 large-12 columns">
        <h4>Clients/Booking</h4>
        <div class="medium-2  columns">BOOKING FOR:</div>
        <div class="medium-2  columns"><b>{{ client.name | upper }} {{ client.lastName | upper }}</b></div>
        <form action="{{ path('booking', {'id_client': client.id}) }}" method="post">
          <div class="medium-1  columns">FROM:</div>
          <div class="medium-2  columns"><input name="form[dateFrom]" value="{{dates.from}}" type="text" class="datepicker" /></div>
          <div class="medium-1  columns">TO:</div>
          <div class="medium-2  columns"><input name="form[dateTo]" value="{{dates.to}}" type="text" class="datepicker" /></div>
          <div class="medium-2  columns"><input class="button" type="submit" value="SEARCH" /></div>
        </form>

        <table class="stack">
          <thead>
            <tr>
              <th width="200">Room</th>
              <th width="200">Availability</th>
              <th width="200">Action</th>
            </tr>
          </thead>
          <tbody>
          {% for room in rooms %}
            <tr>
              <td>{{room.name}}</td>
              <td>
                <div class="callout success">
                    <h7>Available</h7>
                </div>
              </td>
              <td>
                <a class="hollow button warning" href="{{ path('book_Room', {'id_client': client.id, 'id_room': room.id, 'date_in': dates.from, 'date_out': dates.to}) }}">BOOK NOW</a>
              </td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    </div>

{% endblock %}

templates/reservation/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <div class="row">
      <div class="medium-12 large-12 columns">
        <h4>Reservations</h4>

        <table class="stack">
          <thead>
            <tr>
              <th width="200">ROOM</th>
              <th width="200">Name</th>
              <th width="200">DATES</th>
              <th width="200">Action</th>
            </tr>
          </thead>
          <tbody>
            {% for reservation in reservations %}
            <tr>
              <td>{{reservation.room.name}}</td>
              <td>{{reservation.client.title | capitalize}}. {{reservation.client.name}} {{reservation.client.lastName}}</td>
              <td>{{ reservation.dateIn | date('M-d-Y') | upper }} to {{ reservation.dateOut | date('M-d-Y') | upper }}</td>
              <td>
                <a class="hollow button alert" href="{{ path('cancel_booking', { 'reservation_id' : reservation.id }) }}" onclick="return confirm('Are you sure you wish to cancel the reservation?')">CANCEL</a>
              </td>
            </tr>
            {% endfor %}
            
          </tbody>
        </table>
      </div>
    </div>

{% endblock %}